// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.22

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.32.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.32.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.32.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.32.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.32.0
	github.com/ThinkportRepo/opentelemetry-solace-oltp v0.0.1
	go.opentelemetry.io/collector/exporter/otlpexporter v0.102.1
	go.opentelemetry.io/collector/processor/batchprocessor v0.102.1
	go.opentelemetry.io/collector/otelcol v0.126.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)








