dist:
  name: oltp-solace
  description: Custom OpenTelemetry Collector with Solace Trace Receiver in OTLP format
  output_path: ./oltp-solace

receivers:
  - gomod: github.com/ThinkportRepo/opentelemetry-solace-oltp v0.0.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.1
