dist:
  name: otelcol-solace
  description: "OpenTelemetry Collector with Solace Receiver"
  output_path: ./dist
  otelcol_version: 0.102.1

receivers:
  - gomod: ./

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.1
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.102.1

extensions:
  - gomod: go.opentelemetry.io/collector/extension/healthcheckextension v0.102.1
