dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.126.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.126.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.126.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.126.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.126.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.126.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.126.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.126.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.126.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.126.0
  - gomod:
      github.com/ThinkportRepo/opentelemetry-solace-otlp/receiver/solaceotlpreceiver main

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
