receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 42s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      load: {}
      network: {}
      paging: {}
      processes: {}
  httpcheck:
    collection_interval: 144s
    initial_delay: 12s
    targets:
      - method: "GET"
        endpoints:
          - "https://opentelemetry.io"
      - method: "GET"
        endpoints:
          - "https://example.com"
          - "https://heise.de"
  filelog:
    include:
      - /var/log/DiagnosticMessages/*
      - /var/lib/docker/containers/*/*.log
    start_at: beginning
    include_file_path: true
    include_file_name: true
    resource:
      service.name: docker-logs
    operators:
      - type: json_parser
        parse_from: body
      - type: move
        from: attributes.container_name
        to: resource.container.name
      - type: move
        from: attributes.container_id
        to: resource.container.id
  solaceotlp:
    host: ${SOLACE_HOST}
    port: ${SOLACE_PORT}
    ssl: ${SOLACE_SSL}
    queue: ${SOLACE_QUEUE}
    username: ${SOLACE_USERNAME}
    password: ${SOLACE_PASSWORD}
    vpn: ${SOLACE_VPN}

processors:
  batch:
    send_batch_size: 512
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 512
  resource:
    attributes:
      - key: host.name
        value: solace-otel-receiver-adv
        action: upsert
      - key: service.name
        value: otel-collector
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert
      - key: service
        from_attribute: service.name
        action: upsert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1
  datadog:
    api:
      key: ${DD_API_KEY}
      site: ${DD_SITE}
    host_metadata:
      enabled: true
    metrics:
      endpoint: https://api.${DD_SITE}
      resource_attributes_as_tags: true
    traces:
      endpoint: https://trace.agent.${DD_SITE}
      trace_buffer: 10000
      span_name_remappings:
        service.name: service
    logs:
      endpoint: https://http-intake.logs.${DD_SITE}
      use_compression: true
      compression_level: 6

service:
  telemetry:
    logs:
      level: debug
      initial_fields:
        component: otelcol
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp, solaceotlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, datadog]
    metrics:
      receivers: [otlp, hostmetrics, httpcheck]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, datadog]
    logs:
      receivers: [otlp, filelog, solaceotlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, datadog]
