receivers:
  solaceotlp:
    host: ${SOLACE_HOST}
    queue: ${SOLACE_QUEUE}
    username: ${SOLACE_USERNAME}
    password: ${SOLACE_PASSWORD}
    vpn: ${SOLACE_VPN}    

processors:
  batch:
    send_batch_size: 512
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 512
  resource:
    attributes:
      - key: host.name
        value: solace-otel-receiver
        action: upsert
      - key: service.name
        value: otel-collector
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert
      - key: service
        from_attribute: service.name
        action: upsert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1
  datadog:
    api:
      key: ${DD_API_KEY}
      site: ${DD_SITE}
    host_metadata:
      enabled: true

service:
  telemetry:
    logs:
      level: debug
      initial_fields:
        component: otelcol
        receiver: solaceotlp
    metrics:
      level: detailed

  pipelines:
    traces:
      receivers: [solaceotlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, datadog]
    logs:
      receivers: [solaceotlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, datadog]
