receivers:
  solaceotlp:
    endpoint: ${SOLACE_HOST}
    queue: ${SOLACE_QUEUE}
    username: ${SOLACE_USERNAME}
    password: ${SOLACE_PASSWORD}
    vpn: ${SOLACE_VPN}

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [solaceotlp]
      exporters: [debug]
    # Logs-Pipeline ist deaktiviert, da nicht benötigt
    # logs:
    #   receivers: [solaceotlp]
    #   exporters: [debug] 