// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

const (
	Type = "solaceotlp"
)

func ComponentID() component.ID {
	return component.NewID(Type)
}

type Metrics struct {
	SolaceotlpReceiverMessagesReceived metric.Int64Counter
	SolaceotlpReceiverMessagesFailed   metric.Int64Counter
}

func NewMetrics(meter metric.Meter) *Metrics {
	return &Metrics{
		SolaceotlpReceiverMessagesReceived: metric.Must(meter.Int64Counter(
			"solaceotlp.receiver.messages.received",
			metric.WithDescription("Number of messages received from Solace"),
			metric.WithUnit("1"),
		)),
		SolaceotlpReceiverMessagesFailed: metric.Must(meter.Int64Counter(
			"solaceotlp.receiver.messages.failed",
			metric.WithDescription("Number of messages that failed to be processed"),
			metric.WithUnit("1"),
		)),
	}
} 