name: Build and Push Docker Image

on:
  push:
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: thinkportrepo/opentelemetry-solace-otlp

jobs:
  build-and-push-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync tags
        run: |
          git fetch --tags --force
          git tag -l | xargs git tag -d
          git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          if git describe --tags --abbrev=0 2>/dev/null; then
            echo "tag=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.get_tag.outputs.tag }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync tags
        run: |
          git fetch --tags --force
          git tag -l | xargs git tag -d
          git fetch --tags

      - name: Get latest tag
        id: get_tag
        shell: pwsh
        run: |
          $tag = git describe --tags --abbrev=0 2>$null
          if ($?) {
            $tag = $tag -replace '^v', ''
            echo "tag=$tag" >> $env:GITHUB_OUTPUT
          } else {
            echo "tag=dev" >> $env:GITHUB_OUTPUT
          }

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          cache: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:windows-${{ steps.get_tag.outputs.tag }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:windows-latest -f Dockerfile.windows .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:windows-${{ steps.get_tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:windows-latest 