  - name: Build and push Docker image (multiarch)
    uses: docker/build-push-action@v5
    with:
      context: .
      push: true
      platforms: linux/amd64
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      file: collector/Dockerfile 