name: Test, Build and Push
description: Test, Build and Push Docker image to GitHub Container Registry

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  release:
    types: [published]
  
jobs:
  test:
    if: (github.event_name == 'push') || (github.event_name == 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true
      - name: Run unit tests
        run: |
          cd receiver/solaceotlpreceiver
          go test -v -coverprofile=coverage.out ./internal/receiver

  build-and-push:
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync tags
        run: |
          git fetch --tags --force
          git tag -l | xargs git tag -d
          git fetch --tags
      - name: Get latest tag
        id: get_tag
        run: |
          if git describe --tags --abbrev=0 2>/dev/null; then
            echo "tag=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi
      - name: Build and Push Docker Image
        uses: ./.github/actions/build-and-push
        with:
          registry: ghcr.io
          image_name: thinkportrepo/opentelemetry-solace-otlp
          tag: ${{ steps.get_tag.outputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
