name: Tests
description: "Run tests for the OpenTelemetry Collector with Solace Receiver"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -v ./...
          go test -v -race ./...

      - name: Generate Coverage Badge
        run: |
          go install github.com/fgrosse/go-coverage-badge@latest
          go-coverage-badge -o receiver/solaceotlpreceiver/coverage.svg coverage.out

      - name: Commit Coverage Badge (optional)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add receiver/solaceotlpreceiver/coverage.svg
          git commit -m "chore: Update coverage badge [skip ci]"
          git push
